- name: Build base configuration
  hosts: all
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
  vars:
    ansible_python_interpreter: "/usr/bin/python2.7"
  tasks:
    - name: Build configuration
      template: src=baseconfig.j2 dest=/tmp/{{ inventory_hostname  }}.conf

    - name: Install template
      junos_install_config:
        host={{ ansible_ssh_host  }}
        port={{ ansible_ssh_port  }}
        user=root
        passwd=Juniper
        comment="configured by ansible"
        file=/tmp/{{ inventory_hostname  }}.conf
        logfile=changes.log

