- name: Get facts
  hosts: PE_Nodes,P_Nodes,CE_Nodes
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
  vars:
    default_user: "ansible"
    default_password: "Ansible"
  tasks:
    - name: get facts
      junos_get_config:
        user: "root"
        passwd: "Juniper"
        host: "{{ ansible_ssh_host }}"
        port: "{{ ansible_ssh_port }}"
        dest: "/tmp/{{ inventory_hostname }}.xml"

