host_name: BR3
host:
  loopback:
    local_ip: 192.168.20.3/32
    iso_net: 49.0000.0000.cccc.0011.00
  interfaces:
    - interface: ge-0/0/1
      description: to PE3
      local_ip: 10.2.0.3/24
      metric: 10
    - interface: ge-0/0/2
      description: to H3
      local_ip: 10.2.34.3/31
      metric: 10
  isis:
    enabled: false
    overload: false
  ospf:
    enabled: fals
  bgp:
    enabled: true
    as: 65002
    peers:
      external:
        65000:
          - ip: 10.2.0.33
      internal: