host_name: CE1
host:
  loopback:
    local_ip: 192.168.10.1/32
    iso_net: 49.0000.0000.cccc.0001.00
  interfaces:
    - interface: ge-0/0/1
      description: to H1
      local_ip: 10.1.12.1/24
      metric: 10
    - interface: ge-0/0/2
      description: to PE1
      local_ip: 10.1.0.0/31
      metric: 10
    - interface: ge-0/0/3
      description: to PE2
      local_ip: 10.1.0.4/31 
      metric: 10
  isis:
    enabled: false
    overload: false
 
