host_name: CE2
host:
  loopback:
    local_ip: 192.168.10.2/32
    iso_net: 49.0000.0000.cccc.0002.00
  interfaces:
    - interface: ge-0/0/1
      description: to H1
      local_ip: 10.1.12.2/24
    - interface: ge-0/0/2
      description: to PE1
      local_ip: 10.1.0.6/31
    - interface: ge-0/0/3
      description: to PE2
      local_ip: 10.1.0.2/31 
