host_name: PE1
host:
  interfaces:
    - interface: lo0
      description: peering loopback
      local_ip: 171.16.0.11/32
    - interface: ge-0/0/1
      description: to CE1
      local_ip: 10.1.0.1/31
    - interface: ge-0/0/2
      description: to CE2
      local_ip: 10.1.0.7/31
    - interface: ge-0/0/3
      description: to PE2
      local_ip: 10.1.100.0/31
    - interface: ge-0/0/4
      description: to P1
      local_ip: 10.1.10.2/31 

