host_name: PE1
host:
  loopback:
    local_ip: 172.16.0.11/32
    iso_net: 49.0000.0000.cccc.0003.00
  interfaces:
    - interface: ge-0/0/1
      description: to CE1
      local_ip: 10.1.0.1/31
      metric: 10
    - interface: ge-0/0/2
      description: to CE2
      local_ip: 10.1.0.7/31
      metric: 10
    - interface: ge-0/0/3
      description: to PE2
      local_ip: 10.1.100.0/31
      metric: 100
    - interface: ge-0/0/4
      description: to P1
      local_ip: 10.1.10.2/31
      metric: 10
  isis:
    enabled: true
    overload: false
  bgp:
    enabled: true
    as: 65000
    peers:
      external:
        65001:
          - ip: 10.1.0.0
          - ip: 10.1.0.6
      internal:
        - ip: 172.16.0.201
        - ip: 172.16.0.202
