host_name: PE3
host:
  loopback:
    local_ip: 171.16.0.33/32
    iso_net: 49.0000.0000.cccc.0009.00
  interfaces:
    - interface: ge-0/0/1
      description: to P1
      local_ip: 10.1.10.9/31
    - interface: ge-0/0/2
      description: to PE4
      local_ip: 10.1.100.12/31
    - interface: ge-0/0/3
      description: to BR3-4
      local_ip: 10.2.0.33/24

