host_name: RR1
host:
  loopback:
    local_ip: 171.16.0.201/32
    iso_net: 49.0000.0000.cccc.0005.00
  interfaces:
    - interface: ge-0/0/1
      description: to P1
      local_ip: 10.1.10.17/31
      metric: 10
    - interface: ge-0/0/2
      description: to RR2
      local_ip: 10.1.10.14/31
      metric: 10
    - interface: ge-0/0/3
      description: to P2
      local_ip: 10.1.10.19/31
      metric: 10
  isis:
    enabled: true
    overload: true
  bgp:
    enabled: true
    as: 65000
    peers:
      external:
      internal:
        - ip: 172.16.0.11
        - ip: 172.16.0.22
        - ip: 172.16.0.33
        - ip: 172.16.0.44
